"""empty message

Revision ID: 009a6520c867
Revises: 73deec9375dc
Create Date: 2020-07-02 20:22:26.368247

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '009a6520c867'
down_revision = '73deec9375dc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('visit', sa.Column('temperature', sa.String(length=120), nullable=False))
    op.create_unique_constraint(None, 'visit', ['temperature'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'visit', type_='unique')
    op.drop_column('visit', 'temperature')
    # ### end Alembic commands ###
