"""empty message

Revision ID: 6622682c9264
Revises: f1935927c28c
Create Date: 2020-06-26 23:31:32.015014

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '6622682c9264'
down_revision = 'f1935927c28c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('password', table_name='business')
    op.add_column('visit', sa.Column('entry_date', sa.DateTime(timezone=120), nullable=False))
    op.add_column('visit', sa.Column('has_covid', sa.Boolean(), nullable=False))
    op.add_column('visit', sa.Column('has_fever', sa.Boolean(), nullable=False))
    op.drop_column('visit', 'result')
    op.drop_column('visit', 'status')
    op.drop_column('visit', 'entry')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('visit', sa.Column('entry', mysql.DATETIME(), nullable=False))
    op.add_column('visit', sa.Column('status', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False))
    op.add_column('visit', sa.Column('result', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False))
    op.drop_column('visit', 'has_fever')
    op.drop_column('visit', 'has_covid')
    op.drop_column('visit', 'entry_date')
    op.create_index('password', 'business', ['password'], unique=True)
    # ### end Alembic commands ###
