"""empty message

Revision ID: e23becd671ed
Revises: 6622682c9264
Create Date: 2020-06-27 18:45:26.362761

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'e23becd671ed'
down_revision = '6622682c9264'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('visitor', sa.Column('first_name', sa.String(length=120), nullable=False))
    op.drop_column('visitor', 'name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('visitor', sa.Column('name', mysql.VARCHAR(length=120), nullable=False))
    op.drop_column('visitor', 'first_name')
    # ### end Alembic commands ###
